version: "3.9"

services:
  src:
    build: 
      args:
        PROJECT: "src"
      context: .
      dockerfile: Dockerfile-dev
    hostname: dev
    stdin_open: true # docker run -i
    tty: true # docker run -t
    secrets:
      - id_rsa
      - gpg_passphrase
      - gpg_private_key
    volumes:
      - ./projects/src:/home/dev/.sync
secrets:
  id_rsa:
    file: .secrets/id_rsa
  gpg_passphrase:
    file: .secrets/gpg_passphrase
  gpg_private_key:
    file: .secrets/gpg_private_key